unbind C-b
set -g prefix C-a

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-u select-pane -U
bind-key -n C-k select-pane -R 

set -g mouse on

set -g default-terminal "xterm-256color"
set -g status-bg colour235
set -g status-fg colour179
set -g status-left-length 50
set -g status-right "#[fg=default][%H:%M %e-%b-%Y]"
