
[font]
size = 15.0
bold.family = "GeistMono Nerd Font Mono"
italic.family = "GeistMono Nerd Font Mono"
bold_italic.family = "GeistMono Nerd Font Mono"
normal.family = "GeistMono Nerd Font Mono"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "Maximized"
padding = {x = 16, y = 16 }

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/poimandres.toml"
]
