live_config_reload = true

[font]
size = 14.0

[font.bold]
family = "GeistMono Nerd Font Mono"

[font.bold_italic]
family = "GeistMono Nerd Font Mono"

[font.italic]
family = "GeistMono Nerd Font Mono"

[font.normal]
family = "GeistMono Nerd Font Mono"

[window]
dynamic_padding = false
decorations = "Buttonless"

[window.padding]
x = 18
y = 16
