live_config_reload = true

import = [
  # uncomment the flavour you want below:
#   "~/.config/alacritty/catppuccin-latte.toml"
#   "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 15.0

[font.bold]
family = "GeistMono Nerd Font Mono"

[font.bold_italic]
family = "GeistMono Nerd Font Mono"

[font.italic]
family = "GeistMono Nerd Font Mono"

[font.normal]
family = "GeistMono Nerd Font Mono"

[window]
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.85
blur = true

[window.padding]
x = 18
y = 18
